In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
filename = r'/Users/t0mkaka/Downloads/voter_data_34 (1).csv'
df = pd.read_csv(filename)
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
df.head()

Shape: (297514, 11)
Columns: ['filename', 'page_number', 'box_number', 'epic_id', 'seq_number', 'voter_name', 'father_name', 'house_number', 'age', 'gender', 'photo_status']

,filename,page_number,box_number,epic_id,seq_number,voter_name,father_name,house_number,age,gender,photo_status
0,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,1,1,WCD2479095,NaN,विमला देवी,प्रयाग पूर्वे,01,55.0,महिला,फोटो उपलब्ध
1,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,1,2,WCD1515741,2.0,अरुण कु यादव,धनिक्लाल यादव,1,36.0,पुरुष,फोटो उपलब्ध
2,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,1,3,WCD1468354,3.0,लारायण यादव,राजकुमार यादव,1,35.0,पुरुष,फोटो उपलब्ध
3,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,1,4,WCD1515683,4.0,रामनाथ यादव,राजेंद्र यादव,1,33.0,पुरुष,फोटो उपलब्ध
4,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,1,5,WCD1515725,5.0,मनोज कु ठाकुर,योगेन्द्र ठाकुर,1,32.0,पुरुष,फोटो उपलब्ध

In [5]:
print(f"Total records: {len(df)}")
print(f"Unique files: {df['filename'].nunique()}")
print(f"Records per file (avg): {len(df) / df['filename'].nunique():.1f}")
df.info()

Total records: 297514
Unique files: 383
Records per file (avg): 776.8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297514 entries, 0 to 297513
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   filename      297514 non-null  object
 1   page_number   297514 non-null  int64
 2   box_number    297514 non-null  int64
 3   epic_id       295718 non-null  object
 4   seq_number    294870 non-null  float64
 5   voter_name    297379 non-null  object
 6   father_name   290386 non-null  object
 7   house_number  296959 non-null  object
 8   age           297396 non-null  float64
 9   gender        297396 non-null  object
 10  photo_status  296351 non-null  object
dtypes: float64(2), int64(2), object(7)
memory usage: 25.0+ MB

In [11]:
print("Missing values per column:")
df.isnull().sum().sort_values()

Missing values per column:

filename           0
page_number        0
box_number         0
age              118
gender           118
voter_name       135
house_number     555
photo_status    1163
epic_id         1796
seq_number      2644
father_name     7128
dtype: int64

In [16]:
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
pd.DataFrame({'Missing %': missing_pct}).round(2)

              Missing %
father_name        2.40
seq_number         0.89
epic_id            0.60
photo_status       0.39
house_number       0.19
voter_name         0.05
age                0.04
gender             0.04
filename           0.00
page_number        0.00
box_number         0.00

So for the contituency 34. We have some missing value. highest of them is in father's name 
I do not need photo_status as it is just empty. So I will just remove it

In [17]:
df = df.drop('photo_status', axis=1)
df.shape

(297514, 10)

In [18]:
print("Sample of the data:")
df.sample(5)

Sample of the data:

,filename,page_number,box_number,epic_id,seq_number,voter_name,father_name,house_number,age,gender
262064,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,447,28,DXZ1321314,808.0,राम सुमारी देवी,अमरनाथ याँदव,116,44.0,महिला
152251,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,414,15,WCD0403410,345.0,मो० मकबूल,मो० हासिम,96,36.0,पुरुष
137422,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,454,9,BR/14/077/651455,39.0,बिकन साह,रघुनी साह,136,65.0,पुरुष
83681,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,199,30,DFV0848515,270.0,रामवतार सिंह,बच्चा सिंह,48,65.0,पुरुष
19722,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,174,11,WCD1231661,389.0,मनीष कुमार,मिधिलेश कुमार मंडल,64,31.0,पुरुष

In [20]:
print("Records with missing critical fields:")
critical_missing = df[df['epic_id'].isnull() | df['voter_name'].isnull()]
print(f"Missing EPIC ID or voter name: {len(critical_missing)} ({len(critical_missing)/len(df)*100:.1f}%)")
critical_missing

Records with missing critical fields:
Missing EPIC ID or voter name: 1929 (0.6%)

,filename,page_number,box_number,epic_id,seq_number,voter_name,father_name,house_number,age,gender
715,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,25,3,NaN,716.0,कविता सूमन,दिनेश प्रसाद सुमन,60,41.0,महिला
920,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,33,3,NaN,33.0,झुलफुलिया देवी,देवेंद्र राम,7,60.0,महिला
950,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,34,3,NaN,63.0,सुरज राम,मधुनी राम,10,47.0,पुरुष
1130,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,40,3,NaN,243.0,कामनी देवी,अबधेश कुमार खन्ना,38,53.0,महिला
1250,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,44,3,NaN,363.0,श्रवन कुमार मेहता,लालबाबु मेहता,58,40.0,पुरुष
...,...,...,...,...,...,...,...,...,...,...
296267,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,43,3,NaN,423.0,रामबालक साह,दशइ साहू,92,51.0,पुरुष
296788,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,61,3,NaN,944.0,सीता देवी,रामउदगार यादव,29,38.0,महिला
296818,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,62,3,NaN,974.0,सोना देवी,ध्यानी साह,38,48.0,महिला
297174,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,74,2,NaN,242.0,श्याम देवी,श्याम कुमार मिश्रा,51,52.0,महिला
297385,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,81,3,NaN,453.0,उमा नाथ झा,भूषण झा,91,70.0,पुरुष

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297514 entries, 0 to 297513
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   filename      297514 non-null  object
 1   page_number   297514 non-null  int64
 2   box_number    297514 non-null  int64
 3   epic_id       295718 non-null  object
 4   seq_number    294870 non-null  float64
 5   voter_name    297379 non-null  object
 6   father_name   290386 non-null  object
 7   house_number  296959 non-null  object
 8   age           297396 non-null  float64
 9   gender        297396 non-null  object
dtypes: float64(2), int64(2), object(6)
memory usage: 22.7+ MB

In [27]:
print("Age distribution:")
df['age'].describe()

Age distribution:

count    297396.000000
mean         43.730175
std          16.007828
min          18.000000
25%          30.000000
50%          41.000000
75%          55.000000
max         107.000000
Name: age, dtype: float64

In [28]:
print("Records with unusual ages:")
df[(df['age'] < 18) | (df['age'] > 100)][['filename', 'voter_name', 'age']].head(10)

Records with unusual ages:

,filename,voter_name,age
5259,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,मदीना खातुन,103.0
20971,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,योगेन्दर सिंह,106.0
25086,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,पलास देवी,105.0
29000,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,गरीब साह,102.0
34726,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,राम किसुन सदाय,101.0
38496,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,ऊमदी देवी,105.0
45126,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,शिवजी मुखिया,105.0
46298,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,सह्देव महतो,103.0
46461,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,पलट महतो,105.0
46464,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,याशोदा देवी,103.0

In [29]:
print("Gender value counts:")
df['gender'].value_counts(dropna=False)

Gender value counts:

gender
पुरुष     158477
महिला     138893
NaN          118
तृतीय         23
महिलाँ         2
महिंला         1
Name: count, dtype: int64

In [32]:
df['gender'] = df['gender'].replace({'महिलाँ': 'महिला', 'महिंला': 'महिला'})
df['gender'].value_counts(dropna=False)

gender
पुरुष    158477
महिला    138896
NaN         118
तृतीय        23
Name: count, dtype: int64

In [31]:
print("Records with missing critical fields:")
critical_missing = df[df[['voter_name', 'age']].isnull().any(axis=1)]
print(f"Records missing critical data: {len(critical_missing)} ({len(critical_missing)/len(df)*100:.1f}%)")
critical_missing[['filename', 'epic_id', 'voter_name', 'age']].head()

Records with missing critical fields:
Records missing critical data: 252 (0.1%)

,filename,epic_id,voter_name,age
1304,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,WCD2393577,NaN,27.0
1550,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,WCD2149946,NaN,36.0
2263,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,WCD2710093,सुनैना कुमारी<br>पति का नाम: शिव कुमार सिंह<br...,NaN
5352,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,WCD2953925,सतेंद्र कुमार पासवान,NaN
5947,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-H...,WCD0477505,NaN,36.0

In [47]:
br_rows = df[df['voter_name'].str.contains('<br>', na=False)]
br_rows[['filename', 'voter_name']].head(20)

,filename,voter_name
9,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,पूजा कुमारी सुमन<br>पिता का नाम:: रमेश प्रसाद सुमन
60,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,राहुल कुमार राम<br>पिता का नाम:: गुगाली राम
72,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,छोटू कुमार शफ़ी<br>अन्य: शिवनारायण शफ़ी
99,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,भुल्ली देवी<br>पति का नाम: सिया राम ठाकुर
150,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,सुजीत कुमार शर्मा<br>पिता का नाम:: अशेखर शर्मा
399,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,फूलो देवी<br>पति का नाम: दिनेश यादव
512,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,दुखी पूर्वे<br>पिता का नाम:: शितल पूर्वे
563,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,अंशु कुमारी<br>पिता का नाम:: मिथिलेश भंडारी
723,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,भुवनेश्वर यादव<br>पिता का नाम:: छेदी यादव
787,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,राकेश कुमार सिंह<br>पिता का नाम:: जयप्रकाश सिंह
880,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,सुशीला देवी<br>पति का नाम: श्री नारायण महतो
948,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,घुरन राम<br>पिता का नाम:: नथुनी राम
1038,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,संजीव कुमार राम<br>पिता का नाम:: उमेदी राम
1040,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,सुजीत कुमार राम<br>पिता का नाम:: उमेदी राम
1110,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,कुसुम देवी<br>पति का नाम: राम आशीष राम
1199,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,गुलाबचंद्र मेहता<br>पिता का नाम:: जगन्नाथ प्रसाद मेहता
1218,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,पुष्पा देवी<br>पति का नाम: ओमशंकर मेहता
1257,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,सुधा देवी<br>पिता का नाम:: विपिन खन्ना
1258,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,मुकेश कुमार खन्ना<br>पिता का नाम:: किशोरी प्रसाद खन्ना
1260,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,कुलदीप खन्ना<br>पिता का नाम:: रामविलास खन्ना

In [48]:
pd.set_option('display.max_colwidth', None)
br_rows[['filename', 'voter_name']].head(20)

,filename,voter_name
9,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,पूजा कुमारी सुमन<br>पिता का नाम:: रमेश प्रसाद सुमन
60,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,राहुल कुमार राम<br>पिता का नाम:: गुगाली राम
72,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,छोटू कुमार शफ़ी<br>अन्य: शिवनारायण शफ़ी
99,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,भुल्ली देवी<br>पति का नाम: सिया राम ठाकुर
150,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,सुजीत कुमार शर्मा<br>पिता का नाम:: अशेखर शर्मा
399,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,फूलो देवी<br>पति का नाम: दिनेश यादव
512,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,दुखी पूर्वे<br>पिता का नाम:: शितल पूर्वे
563,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,अंशु कुमारी<br>पिता का नाम:: मिथिलेश भंडारी
723,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,भुवनेश्वर यादव<br>पिता का नाम:: छेदी यादव
787,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,राकेश कुमार सिंह<br>पिता का नाम:: जयप्रकाश सिंह
880,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,सुशीला देवी<br>पति का नाम: श्री नारायण महतो
948,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,घुरन राम<br>पिता का नाम:: नथुनी राम
1038,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,संजीव कुमार राम<br>पिता का नाम:: उमेदी राम
1040,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,सुजीत कुमार राम<br>पिता का नाम:: उमेदी राम
1110,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,कुसुम देवी<br>पति का नाम: राम आशीष राम
1199,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,गुलाबचंद्र मेहता<br>पिता का नाम:: जगन्नाथ प्रसाद मेहता
1218,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,पुष्पा देवी<br>पति का नाम: ओमशंकर मेहता
1257,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,सुधा देवी<br>पिता का नाम:: विपिन खन्ना
1258,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,मुकेश कुमार खन्ना<br>पिता का नाम:: किशोरी प्रसाद खन्ना
1260,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,कुलदीप खन्ना<br>पिता का नाम:: रामविलास खन्ना

In [49]:
br_rows[['voter_name']]

                                                voter_name
9       पूजा कुमारी सुमन<br>पिता का नाम:: रमेश प्रसाद सुमन
60             राहुल कुमार राम<br>पिता का नाम:: गुगाली राम
72                 छोटू कुमार शफ़ी<br>अन्य: शिवनारायण शफ़ी
99               भुल्ली देवी<br>पति का नाम: सिया राम ठाकुर
150         सुजीत कुमार शर्मा<br>पिता का नाम:: अशेखर शर्मा
...                                                    ...
297062   कृष्ण कुमार ठाकुर<br>पिता का नाम:: रवीन्द्र ठाकुर
297163                फू ल देवी<br>पति का नाम: भैरव मिश्रा
297413           गुड्रू कुमार झा<br>पिता का नाम:: दिनेश झा
297421                  फूल देवी<br>पति का नाम: कुमर मिश्र
297495            श्रुति श्री<br>पिता का नाम:: श्रीमोहन झा

[4733 rows x 1 columns]

In [50]:
def clean_voter_name_and_father(row):
    if pd.isna(row['voter_name']) or '<br>' not in str(row['voter_name']): return row
    parts = row['voter_name'].split('<br>')
    if len(parts) >= 2:
        row['voter_name'] = parts[0].strip()
        father_part = parts[1].strip()
        for prefix in ['पति का नाम', 'पिता का नाम', 'अन्य']:
            if prefix in father_part:
                father_name = father_part.split(prefix)[-1].lstrip(':').strip()
                if pd.isna(row['father_name']) or row['father_name'] == '': row['father_name'] = father_name
                break
    return row

br_rows = br_rows.apply(clean_voter_name_and_father, axis=1)
br_rows[br_rows['voter_name'].str.contains('<br>', na=False)][['voter_name', 'father_name']].head(10)

Empty DataFrame
Columns: [voter_name, father_name]
Index: []

In [51]:
br_rows.head(20)

,filename,page_number,box_number,epic_id,seq_number,voter_name,father_name,house_number,age,gender
9,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,1,10,WCD2709368,10.0,पूजा कुमारी सुमन,रमेश प्रसाद सुमन,01,23.0,महिला
60,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,3,1,WCD2740611,61.0,राहुल कुमार राम,गुगाली राम,4,23.0,पुरुष
72,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,3,13,WCD2474153,73.0,छोटू कुमार शफ़ी,शिवनारायण शफ़ी,06,24.0,पुरुष
99,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,4,10,BR/14/077/252141,100.0,भुल्ली देवी,सिया राम ठाकुर,10,52.0,महिला
150,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,6,1,WCD2234854,151.0,सुजीत कुमार शर्मा,अशेखर शर्मा,15,27.0,पुरुष
399,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,14,10,WCD1278589,400.0,फूलो देवी,दिनेश यादव,69,35.0,महिला
512,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,18,10,BR/14/077/252038,513.0,दुखी पूर्वे,शितल पूर्वे,18,70.0,पुरुष
563,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,20,1,WCD2128155,564.0,अंशु कुमारी,मिथिलेश भंडारी,27,26.0,महिला
723,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,25,11,BR/14/077/252318,724.0,भुवनेश्वर यादव,छेदी यादव,62,89.0,पुरुष
787,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,27,15,WCD1845452,788.0,राकेश कुमार सिंह,जयप्रकाश सिंह,72,33.0,पुरुष
880,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,31,1,WCD2907921,881.0,सुशीला देवी,श्री नारायण महतो,02,40.0,महिला
948,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,34,1,WCD0464958,61.0,घुरन राम,नथुनी राम,10,49.0,पुरुष
1038,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,37,1,WCD2055002,151.0,संजीव कुमार राम,उमेदी राम,19,28.0,पुरुष
1040,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,37,3,WCD27388888,153.0,सुजीत कुमार राम,उमेदी राम,19,25.0,पुरुष
1110,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,39,13,WCD2073245,223.0,कुसुम देवी,राम आशीष राम,35,52.0,महिला
1199,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,42,12,BR/14/077/468236,312.0,गुलाबचंद्र मेहता,जगन्नाथ प्रसाद मेहता,52,75.0,पुरुष
1218,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,43,1,WCD1345685,331.0,पुष्पा देवी,ओमशंकर मेहता,53,32.0,महिला
1257,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,44,10,WCD0578963,370.0,सुधा देवी,विपिन खन्ना,59,40.0,महिला
1258,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,44,11,WCD1345347,371.0,मुकेश कुमार खन्ना,किशोरी प्रसाद खन्ना,59,37.0,पुरुष
1260,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,44,13,WCD1344902,373.0,कुलदीप खन्ना,रामविलास खन्ना,61,62.0,पुरुष

In [52]:
df = df.apply(clean_voter_name_and_father, axis=1)
df[df['voter_name'].str.contains('<br>', na=False)][['voter_name', 'father_name']].head(10)

Empty DataFrame
Columns: [voter_name, father_name]
Index: []

In [54]:
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
pd.DataFrame({'Missing %': missing_pct}).round(2)

              Missing %
seq_number         0.89
father_name        0.82
epic_id            0.60
house_number       0.19
voter_name         0.05
age                0.04
gender             0.04
filename           0.00
page_number        0.00
box_number         0.00

I have reduced the father\_name to the 2nd position now which is good.

In [56]:
missing_father = df[df['father_name'].isnull()]
print(f"Records with missing father names: {len(missing_father)} ({len(missing_father)/len(df)*100:.1f}%)")
missing_father[['filename', 'voter_name', 'father_name', 'house_number']].head(20)

Records with missing father names: 2437 (0.8%)

,filename,voter_name,father_name,house_number
260,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,रीना देवी,NaN,29
402,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-106-WI.pdf,प्रदीप कुमार यादव,NaN,69
1576,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-234-WI.pdf,अमित कुमार दास,NaN,102
2002,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-151-WI.pdf,द्रोपदी देवी,NaN,87
2114,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-151-WI.pdf,सुंदरी देवी,NaN,113
2583,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,अनील कुमार राय,NaN,52
2592,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,गुलाव देवी,NaN,53
2593,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,सरोज कुमार राय,NaN,53
2667,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,राकेश कुमार राय,NaN,62
2676,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,सरस्वती देवी,NaN,63
2754,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,रेखा देवी,NaN,87
2755,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,विनीया देवी,NaN,87
2795,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,किरण कुमारी,NaN,308
2804,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-375-WI.pdf,काजल देवी,NaN,वार्ड-2
3032,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,बीरू कुमार शफ़ी,NaN,170
3242,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,उमेश महतो,NaN,सुकनी देवी<br>मकान संख्या : पिर्ही
3602,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,शिव कुमार राय,NaN,218
3628,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,खुशी कुमारी,NaN,पिरही
3631,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,शिवम कुमार,NaN,पिहीं
3641,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,खुशबू कुमारी,NaN,वार्ड नंबर 14

In [62]:
br_house = df[df['house_number'].str.contains('<br>', na=False)]
pd.set_option('display.max_colwidth', None)
br_house[[ 'father_name','house_number', 'gender','age']]

,father_name,house_number,gender,age
3242,NaN,सुकनी देवी<br>मकान संख्या : पिर्ही,पुरुष,23.0
5352,शिवजी पासवान,तूलसियाही<br>उम्र : 26 लिंग: : पुरुष,NaN,NaN
11280,मनोज कुमार सिंह,सुक्की<br>उम्र : 28 लिंग: : महिला,NaN,NaN
11281,राजलाल सिंह,सुक्की<br>उम्र : 27 लिंग: : पुरुष,NaN,NaN
45764,शिवनाथ सिंह,वार्ड नं -01<br>उम्र : 20 लिंग: : पुरुष,NaN,NaN
47901,अरुण कुमार यादव,वार्ड नं-10<br>उम्र : 18 लिंग: : पुरुष,NaN,NaN
54800,राम प्रसाद सहनी,82<br>उम्र : 27 लिंग: : पुरुष,NaN,NaN
55420,चंदेश्वर यादव,कुकुपट्टी हाई स्कूल<br>उम्र : 21 लिंग: : पुरुष,NaN,NaN
55421,तीर्थ यादव,कुक्रुपट्टी हाई स्कूल<br>उम्र : 20 लिंग: : पुरुष,NaN,NaN
67966,गणेश कुमार पंडित,145<br>उम्र : 21 लिंग: : महिला,NaN,NaN
89660,ಮಹೇಂದ್ರಪಂಸ್ಕೂನ್,वार्ड 3<br>उम्र : 24 लिंग: : पुरुष,NaN,NaN
141360,जितेंद्र झा,वार्ड नं. 07<br>उम्र : 20 लिंग: : पुरुष,NaN,NaN
158000,राम कुमार मेहता,भूपट्टी<br>उम्र : 19 लिंग: : पुरुष,NaN,NaN
162608,हरिश्चंद्र कुमार,74<br>उम्र : 21 लिंग: : महिला,NaN,NaN
169630,गरभु सिंह,वार्ड नं 12<br>उम्र : 28 लिंग: : पुरुष,NaN,NaN
171459,लक्ष्मी साह,ठाढी<br>उम्र : 25 लिंग: : पुरुष,NaN,NaN
179380,हरिंद्र चौधरी,वार्ड नं-05<br>उम्र : 20 लिंग: : पुरुष,NaN,NaN
187876,संजय कुमार यादव,वार्ड नं-11<br>उम्र : 19 लिंग: : पुरुष,NaN,NaN
206553,शंभू कुमार मंडल,मुरहद्दी छौटकी टोल<br>उम्र : 19 लिंग: : महिला,NaN,NaN
206554,सूर्या नारायण राय राय,सूरहा<br>उम्र : 25 लिंग: : पुरुष,NaN,NaN
208221,कृष्णदेव कुमार,134/135<br>उम्र : 26 लिंग: : महिला,NaN,NaN
212484,NaN,राम कुमार<br>मकान संख्या : वार्ड नं -11,पुरुष,20.0
216026,शंभू यादव,शंभू यादव<br>उम्र : 37 लिंग: : महिला,NaN,NaN
219994,दुर्गेश कुमार मंडल,वार्ड नं. 06<br>उम्र : 30 लिंग: : महिला,NaN,NaN
227711,मनोज कुमार महाराज,गृह नं 75<br>उम्र : 22 लिंग: : पुरुष,NaN,NaN
228858,अर्जुन राउत,वार्ड नं -06<br>उम्र : 18 लिंग: : पुरुष,NaN,NaN
249055,त्रिभुवन प्रसाद गुप्ता,वार्ड नं. - 05<br>उम्र : 23 लिंग: : पुरुष,NaN,NaN
250261,NaN,कूलहरिया<br>उम्र : 24 लिंग: : पुरुष,NaN,NaN
260042,सुभाष कुमार,सुक्की<br>उम्र : 21 लिंग: : महिला,NaN,NaN
268487,ब्रह्मानंद झा,गृह संख्या - 24<br>उम्र : 19 लिंग: : पुरुष,NaN,NaN
281264,राम अवतार यादव,गुह57<br>उम्र : 19 लिंग: : पुरुष,NaN,NaN
281265,राम प्रकाश ठाकुर,गुह61<br>उम्र : 26 लिंग: : पुरुष,NaN,NaN
283856,राम बाबु महतो,वार्ड नं-05<br>उम्र : 21 लिंग: : पुरुष,NaN,NaN

In [65]:
import re
def clean_house_data(df_subset):
    df_clean = df_subset.copy()
    for idx, row in df_clean.iterrows():
        if idx == 3242:
            df_clean.at[idx, 'father_name'] = 'सुकनी देवी'
            df_clean.at[idx, 'house_number'] = 'पिर्ही'
        elif idx == 212484:
            df_clean.at[idx, 'father_name'] = 'राम कुमार'
            df_clean.at[idx, 'house_number'] = 'वार्ड नं -11'
        elif pd.notna(row['house_number']) and '<br>' in str(row['house_number']):
            parts = row['house_number'].split('<br>')
            if len(parts) >= 2:
                df_clean.at[idx, 'house_number'] = parts[0].strip()
                info_part = parts[1].strip()
                age_match = re.search(r'उम्र\s*:\s*(\d+)', info_part)
                gender_match = re.search(r'लिंग:\s*:\s*([^\s]+)', info_part)
                if age_match: df_clean.at[idx, 'age'] = float(age_match.group(1))
                if gender_match: df_clean.at[idx, 'gender'] = gender_match.group(1)
    return df_clean

br_house_cleaned = clean_house_data(br_house)
br_house_cleaned[['father_name', 'house_number', 'age', 'gender']]

                    father_name           house_number   age gender
3242                 सुकनी देवी                 पिर्ही  23.0  पुरुष
5352               शिवजी पासवान              तूलसियाही  26.0  पुरुष
11280           मनोज कुमार सिंह                 सुक्की  28.0  महिला
11281               राजलाल सिंह                 सुक्की  27.0  पुरुष
45764               शिवनाथ सिंह           वार्ड नं -01  20.0  पुरुष
47901           अरुण कुमार यादव            वार्ड नं-10  18.0  पुरुष
54800           राम प्रसाद सहनी                     82  27.0  पुरुष
55420             चंदेश्वर यादव    कुकुपट्टी हाई स्कूल  21.0  पुरुष
55421                तीर्थ यादव  कुक्रुपट्टी हाई स्कूल  20.0  पुरुष
67966          गणेश कुमार पंडित                    145  21.0  महिला
89660           ಮಹೇಂದ್ರಪಂಸ್ಕೂನ್                वार्ड 3  24.0  पुरुष
141360              जितेंद्र झा           वार्ड नं. 07  20.0  पुरुष
158000          राम कुमार मेहता                भूपट्टी  19.0  पुरुष
162608         हरिश्चंद्र कुमार                     74  21.0  महिला
169630                गरभु सिंह            वार्ड नं 12  28.0  पुरुष
171459              लक्ष्मी साह                   ठाढी  25.0  पुरुष
179380            हरिंद्र चौधरी            वार्ड नं-05  20.0  पुरुष
187876          संजय कुमार यादव            वार्ड नं-11  19.0  पुरुष
206553          शंभू कुमार मंडल     मुरहद्दी छौटकी टोल  19.0  महिला
206554    सूर्या नारायण राय राय                  सूरहा  25.0  पुरुष
208221           कृष्णदेव कुमार                134/135  26.0  महिला
212484                राम कुमार           वार्ड नं -11  20.0  पुरुष
216026                शंभू यादव              शंभू यादव  37.0  महिला
219994       दुर्गेश कुमार मंडल           वार्ड नं. 06  30.0  महिला
227711        मनोज कुमार महाराज              गृह नं 75  22.0  पुरुष
228858              अर्जुन राउत           वार्ड नं -06  18.0  पुरुष
249055   त्रिभुवन प्रसाद गुप्ता         वार्ड नं. - 05  23.0  पुरुष
250261                      NaN               कूलहरिया  24.0  पुरुष
260042              सुभाष कुमार                 सुक्की  21.0  महिला
268487            ब्रह्मानंद झा        गृह संख्या - 24  19.0  पुरुष
281264           राम अवतार यादव                  गुह57  19.0  पुरुष
281265         राम प्रकाश ठाकुर                  गुह61  26.0  पुरुष
283856            राम बाबु महतो            वार्ड नं-05  21.0  पुरुष

In [66]:
df.iloc[250261,:]

filename        2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-369-WI.pdf
page_number                                                              43
box_number                                                                7
epic_id                                                          WCD2858165
seq_number                                                            551.0
voter_name                                                     मंजेश पासवान
father_name                                                             NaN
house_number                            कूलहरिया<br>उम्र : 24 लिंग: : पुरुष
age                                                                     NaN
gender                                                                  NaN
Name: 250261, dtype: object

In [67]:
df = clean_house_data(df)
print(f"Remaining records with <br> in house_number: {df['house_number'].str.contains('<br>', na=False).sum()}")
df[df.index.isin([3242, 212484])][['father_name', 'house_number', 'age', 'gender']]

Remaining records with <br> in house_number: 0

       father_name  house_number   age gender
3242    सुकनी देवी        पिर्ही  23.0  पुरुष
212484   राम कुमार  वार्ड नं -11  20.0  पुरुष

In [68]:
for col in df.columns:
    br_count = df[col].astype(str).str.contains('<br>', na=False).sum()
    if br_count > 0: print(f"{col}: {br_count} records with <br>")

father_name: 362 records with <br>

In [76]:
br_father = df[df['father_name'].str.contains('<br>', na=False)]
pd.set_option('display.max_colwidth', None)
br_father[['filename', 'voter_name', 'father_name']].sample(20)

,filename,voter_name,father_name
143183,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-138-WI.pdf,संजू देवी,भुवनेश्वर सिंह<br>मकान संख्या : 30
137380,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-264-WI.pdf,ललिता देवी,पप्पू साहू<br>मकान संख्या : मदनडोभ नवटोली
160120,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-277-WI.pdf,बिभा देवी,सुमन कुमार साह<br>मकान संख्या : 07 बालीराजपुर
3629,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-230-WI.pdf,संगम कुमारी,गुड्रू मिश्रा<br>मकान संख्या : पिर्ही
197822,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-279-WI.pdf,कुमकुम देवी,सुभ नारायण मिश्र<br>मकान संख्या : 70
94411,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-337-WI.pdf,नैन तारा देवी,गगन कुमार<br>मकान संख्या : वार्ड नं-03
53863,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-24-WI.pdf,पुनीता देवी,मुकेश कुमार चौधरी<br>मकान संख्या : वार्ड नं 11
76911,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-17-WI.pdf,महेश मुखिया,मुंगेलाल मुखिया<br>मकान संख्या : 52
11975,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-18-WI.pdf,बिनायका कुमारी,सत्रुधन कुमार यादव<br>मकान संख्या : 15
26185,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-160-WI.pdf,शिवम कुमार सिंह,शंभू कुमार सिंह<br>मकान संख्या : वार्ड नं 13
62686,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-164-WI.pdf,रानी कुमारी,दुखरन मंडल<br>मकान संख्या : वार्ड 12
181871,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-349-WI.pdf,रमेश कुमार यादव,सुखी यादव<br>मकान संख्या : वार्ड नं-04
68915,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-56-WI.pdf,सुजीता कुमारी,धर्मेंद्र कुमार सिंह<br>मकान संख्या : वार्ड नं 3. कमेपट्टी
13831,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-110-WI.pdf,संजीदा खातुन,मोहम्मद इलियास अंसारी<br>मकान संख्या : वार्ड न 9
57902,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-248-WI.pdf,सुभाष कुमार,दुर्गा नंद राय<br>मकान संख्या : 11
235203,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-281-WI.pdf,रणजीत कुमार कामती,पुहुप लाल कॉमती<br>मकान संख्या : 117
170212,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-37-WI.pdf,उत्कर्ष,कृष्ण कुमार<br>मकान संख्या : वार्ड ने 01
169646,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-37-WI.pdf,सत्यदेव साह,शुभनारायण शाह<br>मकान संख्या : 05
198684,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-28-WI.pdf,संजू देवी,कृष्ण कुमार साह<br>मकान संख्या : 02
194350,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-96-WI.pdf,बिटू सिंह,सुनील कुमार सिंह<br>मकान संख्या : वार्ड नं-01

In [77]:
def analyze_father_name_br(df):
    br_father = df[df['father_name'].str.contains('<br>', na=False)].copy()
    single_br = br_father[br_father['father_name'].str.count('<br>') == 1]
    multiple_br = br_father[br_father['father_name'].str.count('<br>') > 1]
    
    print(f"Single <br> cases: {len(single_br)}")
    print(f"Multiple <br> cases: {len(multiple_br)}")
    
    if len(multiple_br) > 0:
        print("\nMultiple <br> cases (need manual handling):")
        for idx, row in multiple_br.iterrows():
            print(f"Index {idx}: {row['father_name']}")
    
    return single_br, multiple_br

single_br, multiple_br = analyze_father_name_br(df)

Single <br> cases: 351
Multiple <br> cases: 11

Multiple <br> cases (need manual handling):
Index 35826: नवीन कुमार ठाकुर<br>मकान संख्या : वार्ड नं.14 बरहा<br>उम्र : 18 लिंग: : महिला
Index 63302: सूरज कुमार<br>मकान संख्या : वार्ड नं - 13<br>उम्र : 25 लिंग: : महिला
Index 74883: मदन कुमार<br>मकान संख्या : वार्ड नं-03<br>उम्र : 19 लिंग: : महिला
Index 88091: सुकदेव पासवान<br>मकान संख्या : वार्ड नं-3<br>उम्र : 19 लिंग: : महिला
Index 103207: सुरेश कुमार राम<br>मकान संख्या : सुरेश कुमार राम<br>उम्र : 28 लिंग: : महिला
Index 105917: राकवा रजन<br>पिता का नाम:: चन्देश्वर प्रसाद सिंह<br>मकान संख्या : वार्ड नं- 03<br>उम्र : 28 लिंग: : पुरुष
Index 113676: गाता द<br>पति का नाम: झरी मंडल<br>मकान संख्या : वार्ड नं-13<br>उम्र : 49 लिंग: : महिला
Index 136789:  फुदुर यादव<br>मकान संख्या : 124<br>उम्र : 55 लिंग: : पुरुष
Index 176254: दायबाखु कु<br>पति का नाम: राघव कुमार झा<br>मकान संख्या : वार्ड नं-06<br>उम्र : 21 लिंग: : महिला
Index 202299: बबलू कुमार यादव<br>मकान संख्या : वार्ड 04<br>उम्र : 23 लिंग: : महिला
Index 279822: सुर्यदेव ठाकुर<br>मकान संख्या : 26<br>उम्र : 43 लिंग: : महिला

In [78]:
def clean_single_br_father(df):
    df_clean = df.copy()
    single_br_mask = df_clean['father_name'].str.contains('<br>', na=False) & (df_clean['father_name'].str.count('<br>') == 1)
    for idx in df_clean[single_br_mask].index:
        parts = df_clean.at[idx, 'father_name'].split('<br>')
        if len(parts) == 2:
            df_clean.at[idx, 'father_name'] = parts[0].strip()
            if pd.isna(df_clean.at[idx, 'house_number']) or df_clean.at[idx, 'house_number'] == '': df_clean.at[idx, 'house_number'] = parts[1].strip()
    return df_clean

df = clean_single_br_father(df)
single_br_after, multiple_br_after = analyze_father_name_br(df)

Single <br> cases: 0
Multiple <br> cases: 11

Multiple <br> cases (need manual handling):
Index 35826: नवीन कुमार ठाकुर<br>मकान संख्या : वार्ड नं.14 बरहा<br>उम्र : 18 लिंग: : महिला
Index 63302: सूरज कुमार<br>मकान संख्या : वार्ड नं - 13<br>उम्र : 25 लिंग: : महिला
Index 74883: मदन कुमार<br>मकान संख्या : वार्ड नं-03<br>उम्र : 19 लिंग: : महिला
Index 88091: सुकदेव पासवान<br>मकान संख्या : वार्ड नं-3<br>उम्र : 19 लिंग: : महिला
Index 103207: सुरेश कुमार राम<br>मकान संख्या : सुरेश कुमार राम<br>उम्र : 28 लिंग: : महिला
Index 105917: राकवा रजन<br>पिता का नाम:: चन्देश्वर प्रसाद सिंह<br>मकान संख्या : वार्ड नं- 03<br>उम्र : 28 लिंग: : पुरुष
Index 113676: गाता द<br>पति का नाम: झरी मंडल<br>मकान संख्या : वार्ड नं-13<br>उम्र : 49 लिंग: : महिला
Index 136789:  फुदुर यादव<br>मकान संख्या : 124<br>उम्र : 55 लिंग: : पुरुष
Index 176254: दायबाखु कु<br>पति का नाम: राघव कुमार झा<br>मकान संख्या : वार्ड नं-06<br>उम्र : 21 लिंग: : महिला
Index 202299: बबलू कुमार यादव<br>मकान संख्या : वार्ड 04<br>उम्र : 23 लिंग: : महिला
Index 279822: सुर्यदेव ठाकुर<br>मकान संख्या : 26<br>उम्र : 43 लिंग: : महिला

In [79]:
df.iloc[105917]

filename                                                        2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-2-WI.pdf
page_number                                                                                                           455
box_number                                                                                                              1
epic_id                                                                                                        WCD1223866
seq_number                                                                                                            NaN
voter_name                                                                                                     राकेश रंजन
father_name     राकवा रजन<br>पिता का नाम:: चन्देश्वर प्रसाद सिंह<br>मकान संख्या : वार्ड नं- 03<br>उम्र : 28 लिंग: : पुरुष
house_number                                                                                                          NaN
age                                                                                                                   NaN
gender                                                                                                                NaN
Name: 105917, dtype: object

In [80]:
def clean_multiple_br_father(df):
    df_clean = df.copy()
    special_indices = [105917, 113676, 176254]
    
    multiple_br_indices = [35826, 63302, 74883, 88091, 103207, 105917, 113676, 136789, 176254, 202299, 279822]
    
    for idx in multiple_br_indices:
        if idx in df_clean.index:
            full_text = df_clean.at[idx, 'father_name']
            if idx in special_indices:
                parts = full_text.split('<br>')
                if len(parts) >= 3:
                    df_clean.at[idx, 'father_name'] = parts[1].split(':')[-1].strip()
                    house_part = parts[2].split(':')[-1].strip() if ':' in parts[2] else parts[2].strip()
                    if pd.isna(df_clean.at[idx, 'house_number']) or df_clean.at[idx, 'house_number'] == '': df_clean.at[idx, 'house_number'] = house_part
                    if len(parts) >= 4:
                        age_gender_part = parts[3]
                        age_match = re.search(r'उम्र\s*:\s*(\d+)', age_gender_part)
                        gender_match = re.search(r'लिंग:\s*:\s*([^\s]+)', age_gender_part)
                        if age_match and (pd.isna(df_clean.at[idx, 'age']) or df_clean.at[idx, 'age'] == ''): df_clean.at[idx, 'age'] = float(age_match.group(1))
                        if gender_match and (pd.isna(df_clean.at[idx, 'gender']) or df_clean.at[idx, 'gender'] == ''): df_clean.at[idx, 'gender'] = gender_match.group(1)
            else:
                parts = full_text.split('<br>')
                if len(parts) >= 3:
                    df_clean.at[idx, 'father_name'] = parts[0].strip()
                    house_part = parts[1].split(':')[-1].strip() if ':' in parts[1] else parts[1].strip()
                    if pd.isna(df_clean.at[idx, 'house_number']) or df_clean.at[idx, 'house_number'] == '': df_clean.at[idx, 'house_number'] = house_part
                    age_gender_part = parts[2]
                    age_match = re.search(r'उम्र\s*:\s*(\d+)', age_gender_part)
                    gender_match = re.search(r'लिंग:\s*:\s*([^\s]+)', age_gender_part)
                    if age_match and (pd.isna(df_clean.at[idx, 'age']) or df_clean.at[idx, 'age'] == ''): df_clean.at[idx, 'age'] = float(age_match.group(1))
                    if gender_match and (pd.isna(df_clean.at[idx, 'gender']) or df_clean.at[idx, 'gender'] == ''): df_clean.at[idx, 'gender'] = gender_match.group(1)
    
    return df_clean

df = clean_multiple_br_father(df)
single_br_final, multiple_br_final = analyze_father_name_br(df)

Single <br> cases: 0
Multiple <br> cases: 0

In [81]:
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
pd.DataFrame({'Missing %': missing_pct}).round(2)

              Missing %
seq_number         0.89
father_name        0.82
epic_id            0.60
house_number       0.06
voter_name         0.05
age                0.03
gender             0.03
filename           0.00
page_number        0.00
box_number         0.00

In [82]:
for col in df.columns:
    br_count = df[col].astype(str).str.contains('<br>', na=False).sum()
    if br_count > 0: print(f"{col}: {br_count} records with <br>")

now no rows with the br tags. So we can start cleaning more.

In [83]:
print("Data quality summary after BR tag cleanup:")
print(f"Total records: {len(df)}")
print(f"Missing values:")
missing_pct = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
pd.DataFrame({'Missing %': missing_pct}).round(2)

Data quality summary after BR tag cleanup:
Total records: 297514
Missing values:

              Missing %
seq_number         0.89
father_name        0.82
epic_id            0.60
house_number       0.06
voter_name         0.05
age                0.03
gender             0.03
filename           0.00
page_number        0.00
box_number         0.00

In [84]:
print("Age distribution:")
print(df['age'].describe())
print(f"\nUnusual ages (< 18 or > 100): {len(df[(df['age'] < 18) | (df['age'] > 100)])}")

Age distribution:
count    297438.000000
mean         43.727503
std          16.008552
min          18.000000
25%          30.000000
50%          41.000000
75%          55.000000
max         107.000000
Name: age, dtype: float64

Unusual ages (< 18 or > 100): 58

In [85]:
print("Gender distribution:")
df['gender'].value_counts(dropna=False)

Gender distribution:

gender
पुरुष    158502
महिला    138913
NaN          76
तृतीय        23
Name: count, dtype: int64

In [88]:
print("Sample house numbers to understand patterns:")
df['house_number'].value_counts().head(20)

Sample house numbers to understand patterns:

house_number
1     3509
12    2863
2     2858
25    2720
13    2702
30    2681
24    2642
50    2639
29    2639
31    2634
10    2634
28    2626
15    2616
27    2603
45    2603
34    2599
44    2585
5     2581
20    2573
22    2570
Name: count, dtype: int64

In [89]:
print("House number length distribution:")
house_lengths = df['house_number'].astype(str).str.len()
house_lengths.describe()

House number length distribution:

count    297514.000000
mean          2.404986
std           1.739086
min           1.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          51.000000
Name: house_number, dtype: float64

In [92]:
print("House numbers with special characters:")
special_chars = df[df['house_number'].str.contains(r'[^\w\s\-/.]', na=False, regex=True)]
special_chars['house_number'].value_counts().head(50)

House numbers with special characters:

house_number
वार्ड नं 11    163
वार्ड नं 12    145
वार्ड नं 09    137
वार्ड नं 07    128
वार्ड नं 06    121
गाढा           119
वार्ड नं 05    119
वार्ड नं 10    115
वार्ड नं 08     97
वार्ड-10        93
वार्ड नं 13     88
वार्ड नं-12     88
वार्ड 12        87
वार्ड 07        87
वार्ड नं 14     85
वार्ड नं-14     81
गाढ़ा           78
वार्ड 10        75
वार्ड नं-13     74
वार्ड नं 04     72
वार्ड नं-05     68
वार्ड नं 01     67
वार्ड नं-11     64
वार्ड-14        63
वार्ड नं 02     62
वार्ड 04        59
वार्ड नं 03     59
वार्ड-12        56
वार्ड नं-04     56
वार्ड-11        55
वार्ड नं-06     54
वार्ड-13        54
वार्ड नं-03     53
वार्ड नं-07     51
वार्ड 06        48
वार्ड-06        47
वार्ड10         47
लदाणिया         45
वार्ड 05        44
चतरा            43
वार्ड-04        42
वार्ड नं-10     42
वार्ड 02        41
वार्ड-07        41
वार्ड-03        41
वार्ड 03        40
वार्ड 08        40
वार्ड नं 5      39
वार्ड           39
वार्ड-05        39
Name: count, dtype: int64

In [93]:
def standardize_ward_numbers(house_number):
    if pd.isna(house_number): return house_number
    house_str = str(house_number).strip()
    if 'वार्ड' in house_str:
        ward_match = re.search(r'वार्ड[^\d]*(\d+)', house_str)
        if ward_match:
            ward_num = int(ward_match.group(1))
            return f"वार्ड-{ward_num:02d}"
    return house_number

df['house_number'] = df['house_number'].apply(standardize_ward_numbers)
df['house_number'].value_counts().head(20)

house_number
1     3509
12    2863
2     2858
25    2720
13    2702
30    2681
24    2642
50    2639
29    2639
10    2634
31    2634
28    2626
15    2616
45    2603
27    2603
34    2599
44    2585
5     2581
20    2573
22    2570
Name: count, dtype: int64

In [94]:
print("House numbers with special characters:")
special_chars = df[df['house_number'].str.contains(r'[^\w\s\-/.]', na=False, regex=True)]
special_chars['house_number'].value_counts().head(50)

House numbers with special characters:

house_number
वार्ड-12           563
वार्ड-07           471
वार्ड-10           465
वार्ड-05           462
वार्ड-06           456
वार्ड-11           440
वार्ड-13           414
वार्ड-09           398
वार्ड-04           380
वार्ड-08           377
वार्ड-03           368
वार्ड-14           362
वार्ड-02           320
वार्ड-01           289
गाढा               119
गाढ़ा               78
वार्ड-15            65
वार्ड-00            55
लदाणिया             45
चतरा                43
वार्ड               39
खरगबनी              35
एकहरी               28
लोहापिपर            27
तूलसियाही           23
छौरही               22
ठाढी                21
बाबूबरही            21
तेघरा               19
भाग नं 279          19
भुरकुरिया           19
चन्द्रडिह           18
ना                  17
वार्ड नं            17
मिश्रौलिया          17
नवटोली              16
बरैल                16
सिधापा              15
तुलसियाही           15
भाग 280             15
गोबरौरा             15
श्यामसिधाप          14
सुक्की              14
भटगामा              13
खोजपुर              13
सहोरवा              13
लदनियां             12
मीर्जापूर           12
मकान संख्या : 7     12
कुसमार              12
Name: count, dtype: int64

In [95]:
makan_rows = df[df['house_number'].str.contains('मकान', na=False)]
makan_rows['house_number'].value_counts().head(20)

house_number
मकान संख्या : 7               12
मकान संख्या : 5                6
मकान संख्या : 14               5
मकान संख्या : 15               5
मकान संख्या : 10               5
मकान संख्या : 50               5
मकान संख्या : 52               4
मकान संख्या : 70               4
मकान संख्या : 106              4
मकान संख्या : मिश्रौलिया       4
मकान संख्या : 104              4
मकान संख्या : 30               4
मकान संख्या : 54               4
मकान संख्या : 25               4
मकान संख्या : 58               3
मकान संख्या : 77               3
मकान संख्या : 75               3
मकान संख्या : ग्राम-शिवनगर     3
मकान संख्या : 17               3
मकान संख्या : 76               3
Name: count, dtype: int64

In [96]:
def standardize_makan_numbers(house_number):
    if pd.isna(house_number): return house_number
    house_str = str(house_number).strip()
    if 'मकान संख्या' in house_str and ':' in house_str:
        parts = house_str.split(':', 1)
        if len(parts) == 2: return parts[1].strip()
    return house_number

df['house_number'] = df['house_number'].apply(standardize_makan_numbers)
df[df['house_number'].str.contains('मकान', na=False)]['house_number'].value_counts().head(10)

house_number
मकान नं 22         2
मकान सं.-52        1
मकान संख्या- 33    1
मकान सं.-111       1
मकान संख्या 76     1
मकान सं0 - 89      1
Name: count, dtype: int64

In [97]:
def standardize_makan_numbers(house_number):
    if pd.isna(house_number): return house_number
    house_str = str(house_number).strip()
    if 'मकान' in house_str:
        makan_match = re.search(r'मकान[^\d]*(\d+)', house_str)
        if makan_match: return makan_match.group(1)
        elif ':' in house_str:
            parts = house_str.split(':', 1)
            if len(parts) == 2: return parts[1].strip()
    return house_number

df['house_number'] = df['house_number'].apply(standardize_makan_numbers)
df[df['house_number'].str.contains('मकान', na=False)]['house_number'].value_counts().head(10)

Series([], Name: count, dtype: int64)

In [98]:
print("House numbers with special characters:")
special_chars = df[df['house_number'].str.contains(r'[^\w\s\-/.]', na=False, regex=True)]
special_chars['house_number'].value_counts().head(50)

House numbers with special characters:

house_number
वार्ड-12      563
वार्ड-07      471
वार्ड-10      465
वार्ड-05      462
वार्ड-06      456
वार्ड-11      440
वार्ड-13      414
वार्ड-09      398
वार्ड-04      380
वार्ड-08      377
वार्ड-03      368
वार्ड-14      362
वार्ड-02      320
वार्ड-01      289
गाढा          119
गाढ़ा          78
वार्ड-15       65
वार्ड-00       55
लदाणिया        48
चतरा           43
वार्ड          40
खरगबनी         35
लोहापिपर       28
एकहरी          28
तूलसियाही      24
छौरही          22
बाबूबरही       21
मिश्रौलिया     21
ठाढी           21
भाग नं 279     19
भुरकुरिया      19
तेघरा          19
चन्द्रडिह      18
ना             17
वार्ड नं       17
नवटोली         16
बरैल           16
गोबरौरा        16
तुलसियाही      15
सिधापा         15
भाग 280        15
सुक्की         14
श्यामसिधाप     14
सहोरवा         13
खोजपुर         13
भटगामा         13
भूपट्टी        12
कुसमार         12
मीर्जापूर      12
लदनियां        12
Name: count, dtype: int64

In [99]:
house_counts = df.groupby(['filename', 'house_number']).size().reset_index(name='people_count')
house_counts_sorted = house_counts.sort_values('people_count', ascending=False)
house_counts_sorted.head(20)

,filename,house_number,people_count
30737,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-309-WI.pdf,254,285
30105,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-304-WI.pdf,00,187
34219,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-332-WI.pdf,1,128
48329,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-85-WI.pdf,1,116
41555,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-382-WI.pdf,7,91
7571,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-154-WI.pdf,2,85
28914,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-298-WI.pdf,2,84
43172,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-49-WI.pdf,गाढा,79
247,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-100-WI.pdf,42,67
49569,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-94-WI.pdf,57,65
30756,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-309-WI.pdf,वार्ड-14,63
24753,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-270-WI.pdf,1,61
15261,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-207-WI.pdf,1,60
21122,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-244-WI.pdf,0,56
13760,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-197-WI.pdf,1,56
23460,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-261-WI.pdf,वार्ड-11,55
11250,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-179-WI.pdf,2,53
15753,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-210-WI.pdf,15,52
43184,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-5-WI.pdf,1,51
41001,2025-EROLLGEN-S04-34-SIR-DraftRoll-Revision1-HIN-379-WI.pdf,26,50